# TAA key genes identification

In [4]:
import pandas as pd

In [7]:
df_sbc4 = pd.read_csv("/Users/daffa/workspace/infobio/thesis/analysis/data/tsv/SBC4.private.annotated.tsv", sep="\t")
df_sbc10 = pd.read_csv("/Users/daffa/workspace/infobio/thesis/analysis/data/tsv/SBC10.private.annotated.tsv", sep="\t")

In [8]:
df_sbc4

,chrom,pos,ref,alt,qual,GT_SBC4,allele,effect,impact,gene_name,...,feature_id,biotype,rank,hgvs_c,hgvs_p,cdna_pos,cds_pos,aa_pos,distance,extra
0,1,487,AG,A,52.849998,1/1,A,upstream_gene_variant,MODIFIER,SORBI_3001G000100,...,EER90453,protein_coding,NaN,c.-1463delG,NaN,NaN,NaN,NaN,1463.0,NaN
1,1,487,AG,A,52.849998,1/1,A,intergenic_region,MODIFIER,CHR_START-SORBI_3001G000100,...,CHR_START-SORBI_3001G000100,NaN,NaN,n.488delG,NaN,NaN,NaN,NaN,NaN,NaN
2,1,997,ATACC,A,64.190002,1/1,A,upstream_gene_variant,MODIFIER,SORBI_3001G000100,...,EER90453,protein_coding,NaN,c.-953_-950delTACC,NaN,NaN,NaN,NaN,953.0,NaN
3,1,997,ATACC,A,64.190002,1/1,A,intergenic_region,MODIFIER,CHR_START-SORBI_3001G000100,...,CHR_START-SORBI_3001G000100,NaN,NaN,n.998_1001delTACC,NaN,NaN,NaN,NaN,NaN,NaN
4,1,2814,G,GT,28.549999,1/1,GT,downstream_gene_variant,MODIFIER,SORBI_3001G000100,...,EER90453,protein_coding,NaN,c.*198_*199insT,NaN,NaN,NaN,NaN,199.0,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2878159,10,61222478,C,T,32.939999,1/1,T,upstream_gene_variant,MODIFIER,SORBI_3010G279900,...,KXG20990,protein_coding,NaN,c.-2876G>A,NaN,NaN,NaN,NaN,2540.0,NaN
2878160,10,61222478,C,T,32.939999,1/1,T,upstream_gene_variant,MODIFIER,SORBI_3010G280100,...,EER89022,protein_coding,NaN,c.-1224C>T,NaN,NaN,NaN,NaN,1062.0,NaN
2878161,10,61222651,C,T,29.969999,1/1,T,missense_variant,MODERATE,SORBI_3010G280000,...,KXG20991,protein_coding,1/1,c.179G>A,p.Ser60Asn,179/891,179/891,60/296,NaN,NaN
2878162,10,61222651,C,T,29.969999,1/1,T,upstream_gene_variant,MODIFIER,SORBI_3010G279900,...,KXG20990,protein_coding,NaN,c.-3049G>A,NaN,NaN,NaN,NaN,2713.0,NaN
2878163,10,61222651,C,T,29.969999,1/1,T,upstream_gene_variant,MODIFIER,SORBI_3010G280100,...,EER89022,protein_coding,NaN,c.-1051C>T,NaN,NaN,NaN,NaN,889.0,NaN

In [11]:
len(df_sbc4[df_sbc4["impact"] == "HIGH"])

3814

In [9]:
df_sbc10

,chrom,pos,ref,alt,qual,GT_SBC10,allele,effect,impact,gene_name,...,feature_id,biotype,rank,hgvs_c,hgvs_p,cdna_pos,cds_pos,aa_pos,distance,extra
0,1,1619,G,A,54.540001,1|0,A,upstream_gene_variant,MODIFIER,SORBI_3001G000100,...,EER90453,protein_coding,NaN,c.-332G>A,NaN,NaN,NaN,NaN,332.0,NaN
1,1,1619,G,A,54.540001,1|0,A,intergenic_region,MODIFIER,CHR_START-SORBI_3001G000100,...,CHR_START-SORBI_3001G000100,NaN,NaN,n.1619G>A,NaN,NaN,NaN,NaN,NaN,NaN
2,1,5784,A,"AGG,AG",25.700001,1/2,AG,downstream_gene_variant,MODIFIER,SORBI_3001G000100,...,EER90453,protein_coding,NaN,c.*3168_*3169insG,NaN,NaN,NaN,NaN,3169.0,NaN
3,1,5784,A,"AGG,AG",25.700001,1/2,AGG,downstream_gene_variant,MODIFIER,SORBI_3001G000100,...,EER90453,protein_coding,NaN,c.*3168_*3169insGG,NaN,NaN,NaN,NaN,3169.0,NaN
4,1,5784,A,"AGG,AG",25.700001,1/2,AG,intergenic_region,MODIFIER,SORBI_3001G000100-SORBI_3001G000200,...,SORBI_3001G000100-SORBI_3001G000200,NaN,NaN,n.5784_5785insG,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
899795,10,61233582,GTT,G,35.779999,1/1,G,intergenic_region,MODIFIER,SORBI_3010G280100-CHR_END,...,SORBI_3010G280100-CHR_END,NaN,NaN,n.61233583_61233584delTT,NaN,NaN,NaN,NaN,NaN,NaN
899796,10,61233615,A,T,29.270000,1/1,T,intergenic_region,MODIFIER,SORBI_3010G280100-CHR_END,...,SORBI_3010G280100-CHR_END,NaN,NaN,n.61233615A>T,NaN,NaN,NaN,NaN,NaN,NaN
899797,10,61233619,T,G,27.490000,1/1,G,intergenic_region,MODIFIER,SORBI_3010G280100-CHR_END,...,SORBI_3010G280100-CHR_END,NaN,NaN,n.61233619T>G,NaN,NaN,NaN,NaN,NaN,NaN
899798,10,61233644,A,AG,35.650002,1/1,AG,intergenic_region,MODIFIER,SORBI_3010G280100-CHR_END,...,SORBI_3010G280100-CHR_END,NaN,NaN,n.61233644_61233645insG,NaN,NaN,NaN,NaN,NaN,NaN
899799,10,61233676,G,GT,32.020000,1/1,GT,intergenic_region,MODIFIER,SORBI_3010G280100-CHR_END,...,SORBI_3010G280100-CHR_END,NaN,NaN,n.61233676_61233677insT,NaN,NaN,NaN,NaN,NaN,NaN

In [10]:
len(df_sbc10[df_sbc10["impact"] == "HIGH"])

1606